# Week 8 · Day 1 — Assignment
# Your First ML Model — Graded 🍷

**Goal:** prove you can run the full 5-step ML recipe on a **new dataset you haven't seen in class**.

This notebook is **portfolio quality** — it goes to your public GitHub. Write clean code and clear markdown. A US recruiter or professor may read it.

**Dataset:** the **Wine** dataset built into scikit-learn. Each row is a wine; the target is which of 3 cultivars (wine types) it came from, based on chemical measurements.

**Marks: 10 total**
- Load & explore (2)
- X / y split (1)
- Train / test split (2)
- Train model (1)
- Predict + accuracy (2)
- Written reflection markdown (2)

> Reminder: keep everything in **English**, add short comments, and run every cell before you push.

## Part 0 — Load the data (given)

Run this cell as-is. It loads the Wine dataset into a clean DataFrame for you.

In [1]:
import pandas as pd
from sklearn.datasets import load_wine

# Load into a DataFrame
data = load_wine(as_frame=True)
wine = data.frame          # features + a 'target' column (0, 1, 2 = wine type)

wine.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

## Part 1 — Explore (2 marks)

Print the **shape** of the dataset, and use `value_counts()` on the `target` column to see how many wines of each type there are.

In [5]:
# YOUR CODE HERE
wine.shape
print("shape of wine:", wine.shape)

# Split the data into features and target
print(wine["target"].value_counts())

shape of wine: (178, 14)
target
1    71
0    59
2    48
Name: count, dtype: int64

In [6]:
wine

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

## Part 2 — Split into X and y (1 mark)

- `X` = every column **except** `target`  *(hint: `wine.drop(columns="target")`)*
- `y` = the `target` column

In [7]:
from sklearn.model_selection import train_test_split

X = wine.drop(columns="target")

y = wine["target"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (178, 13)
y shape: (178,)

## Part 3 — Train / Test split (2 marks)

Hold out **20%** for testing. Use `random_state=42`.

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.11, random_state=42
)

print("Training examples:", X_train.shape[0])
print("Testing examples: ", X_test.shape[0])

Training examples: 158
Testing examples:  20

## Part 4 — Train a KNN model (1 mark)

Use `n_neighbors=5`. Fit it on the training data.

In [13]:
from sklearn.neighbors import KNeighborsClassifier
# Create the model
model = KNeighborsClassifier(n_neighbors=5)

# Train it
model.fit(X_train, y_train)

print("Trained! ✅")

Trained! ✅

## Part 5 — Predict and score (2 marks)

Predict on the test set and print the accuracy as a percentage.

In [14]:
from sklearn.metrics import accuracy_score

predictions = model.predict(X_test)
acc = accuracy_score(y_test, predictions)
print(f"Accuracy: {acc*100:.0f}%")

Accuracy: 75%

## Part 6 — Reflection (2 marks) ✍️

Double-click this cell and answer in your own words (3–5 sentences):

1. What were the **features** and what was the **target** in this problem?
2. What accuracy did your model reach?
3. In one sentence: why do we keep a separate **test set** instead of scoring on the training data?

*Your answer here:*

"Is problem mein features wine ke chemical measurements thay (jaise alcohol, acidity, phenols, waghera — target ke ilawa sab columns), aur target wine ki class/category thi jo predict karni thi. Mere model ne 75% accuracy hasil ki. Hum separate test set is liye rakhte hain kyunke agar hum training data pe hi score karein to model sirf woh data yaad kar sakta hai jo usne dekha hai, jis se accuracy misleading tor par zyada dikh sakti hai — asli test yeh hai ke model naye, unseen data pe kitna acha perform karta hai."


---
**Submit:** push this notebook to a new GitHub repo (e.g. `code-to-ai-first-ml-model`) and post the repo link in the WhatsApp group. 🚀