# Week 8 · Day 1 — Practice
# Build the 5-Step ML Recipe Yourself 🛠️

In class we built a KNN model on Iris together. Now **you** drive.

The structure is here; you fill in the blanks marked `# YOUR CODE HERE`. Follow the same 5 steps from class. Run each cell as you go.

> Tip: keep the class notebook open next to this one if you get stuck.

In [2]:
!pip install scikit-learn -q

^C

In [3]:
# Toolkit — run this cell as-is
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

iris = sns.load_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Warm-up: explore the data

Print the shape, and show how many flowers of each species there are.

In [4]:
# 1) Print the shape of the dataset
# YOUR CODE HERE
iris.shape
print("shape of iris:", iris.shape)


# 2) Count how many flowers of each species (hint: value_counts on the 'species' column)
# YOUR CODE HERE
species_counts = iris['species'].value_counts()
print("Number of flowers of each species:")
print(species_counts)

shape of iris: (150, 5)
Number of flowers of each species:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Step 1 — Features (X) and Target (y)

Put the four measurement columns in `X` and the `species` column in `y`.

In [6]:
# X = the four measurement columns
X = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

# y = the species column
y = iris['species']

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (150, 4)
y shape: (150,)

In [7]:
!pip install scikit-learn -q

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Step 2 — Train / Test split

Hold out **25%** for testing this time. Use `random_state=42`.

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.165, random_state=42
)

print("Training examples:", X_train.shape[0])
print("Testing examples: ", X_test.shape[0])

Training examples: 125
Testing examples:  25

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

### Step 3 — Create and train a KNN model

Use **3** neighbors this time (`n_neighbors=3`), then `.fit()` on the training data.

In [28]:
from sklearn.neighbors import KNeighborsClassifier
# Create the model
model = KNeighborsClassifier(n_neighbors=3)

# Train it
model.fit(X_train, y_train)

print("Trained! ✅")

Trained! ✅

### Step 4 — Predict on the test set

In [19]:
predictions = model.predict(X_test)
predictions[:10]

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor'],
      dtype=object)

### Step 5 — Score it

Compute and print the accuracy as a percentage.

In [27]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, predictions)
print(f"Accuracy: {acc*100:.0f}%")
print(f"accuracy:, {acc}")

Accuracy: 100%
accuracy:, 1.0

### Bonus — predict a new flower

Make up one flower's four measurements and predict its species.

In [22]:
new_flower = pd.DataFrame(
    [[6.0, 2.7, 5.1, 1.6]],
    columns=["sepal_length", "sepal_width", "petal_length", "petal_width"]
)

# Predict and print the result
new_flower

   sepal_length  sepal_width  petal_length  petal_width
0           6.0          2.7           5.1          1.6

### 🧠 Think about it (write your answer below)

You used **3** neighbors here and we used **5** in class. Did the accuracy change?

Double-click this cell and type 2–3 sentences on what you noticed.

*Your answer:*

Jab humne k ko 3 se 5 kiya, to accuracy same rahi — 100%. Yeh isliye hua kyunke Iris dataset ki teeno species (setosa, versicolor, virginica) apne sepal aur petal measurements ke hisaab se kaafi clearly separate hain, is liye chahe kam neighbors dekhein ya zyada, model har baar sahi species pehchan leta hai. Test set bhi chota tha, is liye har prediction correct hone ka chance zyada tha."